package Presentacion;

import BusinessObject.Empleado;
import BusinessObject.RolUsuario;
import BusinessObject.Usuario;
import DataAccessObject.EmpleadoDAO;
import DataAccessObject.RolUsuarioDAO;
import DataAccessObject.UsuarioDAO;
import TransferObject.EmpleadoDTO;
import TransferObject.RolUsuarioDTO;
import TransferObject.UsuarioDTO;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author KEVIN EP
 */
public class frameVendedor extends javax.swing.JFrame {

    private UsuarioDTO dtoUsuario;
    private EmpleadoDTO dtoEmpleado;
    private RolUsuarioDTO dtoRolUsuario;
    private UsuarioDAO daoUsuario;
    private EmpleadoDAO daoEmpleado;
    private RolUsuarioDAO daoRolEmpleado;
    private Usuario oUsuario;
    private Empleado oEmpleado;
    private RolUsuario oRolUsuario;
    private int codUsuario, codRolUsuario;
    private String codEmpleado;

    public frameVendedor(UsuarioDTO dtoUsuario) {
        daoEmpleado = new EmpleadoDAO();
        daoRolEmpleado = new RolUsuarioDAO();
        daoUsuario = new UsuarioDAO();
        codEmpleado = dtoUsuario.getCodEmpleado();
        codUsuario = dtoUsuario.getCodUsuario();
        codRolUsuario = dtoUsuario.getCodRolUsuario();
        initComponents();
        inicarFrameVendedor();
    }

    public frameVendedor() {
        initComponents();
    }

    private void inicarFrameVendedor() {
        this.setLocationRelativeTo(null);
        this.setTitle("Vendedor - Sistema de Gestión de Clientes");
        oEmpleado = new Empleado();
        oRolUsuario = new RolUsuario();
        oUsuario = new Usuario();

        dtoEmpleado = oEmpleado.buscar(codEmpleado);
        dtoRolUsuario = oRolUsuario.buscar(codRolUsuario);
        dtoUsuario = oUsuario.buscar(codUsuario);

        labelNombresEmpleado.setText(dtoEmpleado.getNombres() + " " + dtoEmpleado.getApellidoPaterno());
        labelRolUsuario.setText(dtoRolUsuario.getNombreRol());
    }

    private void mostrarPanel(JPanel jPanel) {
        jPanel.setSize(1024, 700);
        jPanel.setLocation(0, 0);
        contenidoJPanel.removeAll();
        contenidoJPanel.add(jPanel, BorderLayout.CENTER);
        contenidoJPanel.revalidate();
        contenidoJPanel.repaint();
    }

    public void seleccionarBoton(boolean botonProductos, boolean botonVentas, boolean botonClientes, boolean botonReportes, boolean botonPerfil) {
        btnProductos.setSelected(botonProductos);
        btnVentas.setSelected(botonVentas);
        btnClientes.setSelected(botonClientes);
        btnReportes.setSelected(botonReportes);
        btnPerfil.setSelected(botonPerfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelRolUsuario = new javax.swing.JLabel();
        labelNombresEmpleado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        contenidoJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(1, 75, 160));

        labelRolUsuario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        labelRolUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelRolUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRolUsuario.setText("ROL");

        labelNombresEmpleado.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelNombresEmpleado.setForeground(new java.awt.Color(237, 237, 237));
        labelNombresEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombresEmpleado.setText("Ful Name");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(200, 200, 200));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hola");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoAbasto187x88.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombresEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRolUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNombresEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 242, -1));

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnProductos.png"))); // NOI18N
        btnProductos.setContentAreaFilled(false);
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnProductosHover.png"))); // NOI18N
        btnProductos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btnProductosSelected.png"))); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 90));

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnVentas.png"))); // NOI18N
        btnVentas.setContentAreaFilled(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnVentasHover.png"))); // NOI18N
        btnVentas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btnVentasSelected.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, 90));

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnClientes.png"))); // NOI18N
        btnClientes.setContentAreaFilled(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnClientesHover.png"))); // NOI18N
        btnClientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btnClientesSelected.png"))); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 90));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnReportes.png"))); // NOI18N
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnReportesHover.png"))); // NOI18N
        btnReportes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btnReportesSelected.png"))); // NOI18N
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 100, 90));

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/btnPerfil2.png"))); // NOI18N
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnPerfil2Hover.png"))); // NOI18N
        btnPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btnPerfil2Selected.png"))); // NOI18N
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 90));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCerrarSesionHover.png"))); // NOI18N
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 218, 40));

        javax.swing.GroupLayout contenidoJPanelLayout = new javax.swing.GroupLayout(contenidoJPanel);
        contenidoJPanel.setLayout(contenidoJPanelLayout);
        contenidoJPanelLayout.setHorizontalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        contenidoJPanelLayout.setVerticalGroup(
            contenidoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(contenidoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        plProductos jpProductos = new plProductos(frameVendedor.this);
        mostrarPanel(jpProductos);
        seleccionarBoton(true, false, false, false, false);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        frameLogin jpLogin = new frameLogin();
        jpLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        plPerfil jpPerfil = new plPerfil(dtoEmpleado, dtoUsuario, dtoRolUsuario, frameVendedor.this);
        mostrarPanel(jpPerfil);
        seleccionarBoton(false, false, false, false, true);

    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
 /*     
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     */
    //</editor-fold>
    //   /* Create and display the form */
    //   java.awt.EventQueue.invokeLater(new Runnable() {
    //       public void run() {
    //            new frameVendedor().setVisible(true);
    //        }
    //    });
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    public javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    public javax.swing.JPanel contenidoJPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel labelNombresEmpleado;
    public javax.swing.JLabel labelRolUsuario;
    // End of variables declaration//GEN-END:variables
}
