package Presentacion;

import BusinessObject.RolUsuario;
import TransferObject.RolUsuarioDTO;
import Utilities.DisabledItemRenderer;
import javax.swing.JOptionPane;

/**
 *
 * @author KEVIN EP
 */
public class panelFormularioUsuario extends javax.swing.JPanel {

    private RolUsuarioDTO dtoRolUsuario;
    private RolUsuario oRolUsuario;

    public panelFormularioUsuario() {
        oRolUsuario = new RolUsuario();
        initComponents();
        llenarComboBox();
        labelCodigoEmpleado.setVisible(false);
        labelCodigoEmpleado.setText("");
        labelNombreApellidoEmpleado.setText("");
    }

    private void llenarComboBox() {
        RolUsuarioDTO mensajeSeleccionStart = new RolUsuarioDTO(0, "-- Seleccione --");
        cbTipoUsuario.addItem(mensajeSeleccionStart);
        for (RolUsuarioDTO rol : oRolUsuario.listar()) {
            cbTipoUsuario.addItem(rol);
        }
        cbTipoUsuario.setRenderer(new DisabledItemRenderer());
    }

    public boolean validarFormularioUsuario() {
        String userName = txtNameUser.getText().trim();
        String password = txtPassword.getText().trim();
        if (cbTipoUsuario.getSelectedIndex() != 0) {
            if (!userName.isEmpty()) {
                if (!password.isEmpty()) {
                    if (rbUsuarioActivo.isSelected() || rbUsuarioInactivo.isSelected()) {
                        return true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Dedes seleccionar un Estado", "¡Error! Datos Incompletos", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Dedes ingresar una contraseña", "¡Error! Datos Incompletos", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Dedes ingresar un Nombre de Usuario", "¡Error! Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Dedes Seleccionar un Rol", "¡Error! Datos Incompletos", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    public void cancelar() {
        cbTipoUsuario.setSelectedIndex(0);
        txtNameUser.setText("");
        txtPassword.setText("");

        rbUsuarioInactivo.setEnabled(true);
        if (rbUsuarioActivo.isSelected()) {
            rbUsuarioActivo.setSelected(false);
        } else if (rbUsuarioInactivo.isSelected()) {
            rbUsuarioInactivo.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupUsuario = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        labelNombreApellidoEmpleado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNameUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rbUsuarioActivo = new javax.swing.JRadioButton();
        rbUsuarioInactivo = new javax.swing.JRadioButton();
        btnCrearUsuario = new javax.swing.JButton();
        labelCodigoEmpleado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 176, 212), 2, true), "DATOS DEL USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(30, 64, 175))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("para: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 36, 30, 20));

        labelNombreApellidoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombreApellidoEmpleado.setForeground(new java.awt.Color(0, 102, 102));
        labelNombreApellidoEmpleado.setText("Nombre Apellido");
        add(labelNombreApellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Rol de Usuario");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 111, 30));

        cbTipoUsuario.setToolTipText("");
        add(cbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 70, 180, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nombre de Usuario:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 115, -1, 30));

        txtNameUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 114, 180, 30));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 157, 180, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Contraseña:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 158, 111, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Estado:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 200, 111, 30));

        buttonGroupUsuario.add(rbUsuarioActivo);
        rbUsuarioActivo.setText("Activo");
        add(rbUsuarioActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 205, -1, -1));

        buttonGroupUsuario.add(rbUsuarioInactivo);
        rbUsuarioInactivo.setText("Inactivo");
        add(rbUsuarioInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 205, -1, -1));

        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/btnCrearUsuario.png"))); // NOI18N
        btnCrearUsuario.setContentAreaFilled(false);
        btnCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/btnCrearUsuarioHover.png"))); // NOI18N
        add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 236, 180, 44));

        labelCodigoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCodigoEmpleado.setForeground(new java.awt.Color(0, 51, 51));
        labelCodigoEmpleado.setText("CODIGO");
        add(labelCodigoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 60, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrearUsuario;
    private javax.swing.ButtonGroup buttonGroupUsuario;
    public javax.swing.JComboBox<RolUsuarioDTO> cbTipoUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel labelCodigoEmpleado;
    public javax.swing.JLabel labelNombreApellidoEmpleado;
    public javax.swing.JRadioButton rbUsuarioActivo;
    public javax.swing.JRadioButton rbUsuarioInactivo;
    public javax.swing.JTextField txtNameUser;
    public javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
