package Presentacion;

import BusinessObject.Categoria;
import TransferObject.CategoriaDTO;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author edgar
 */
public class plCategoria extends javax.swing.JPanel {

    private Categoria oCategoria;
    private DefaultTableModel modeloCategoria;
    private frameAdministrador jFrameAdmin;
    private frameVendedor jFrameVededor;
    TableRowSorter trs;
    /**
     * Creates new form plCategoria
     *
     * @param jFrame
     */
    public plCategoria(JFrame jFrame) {
        jFrameAdmin = new frameAdministrador();
        jFrameVededor = new frameVendedor();
        if (jFrame.getClass() == jFrameAdmin.getClass()) {
            this.jFrameAdmin = (frameAdministrador) jFrame;
        } else {
            this.jFrameVededor = (frameVendedor) jFrame;
        }
        modeloCategoria = new DefaultTableModel();
        oCategoria = new Categoria();
        initComponents();

        iniciarPanelCategoria();
        listarCategoria();

    }

    private void iniciarPanelCategoria() {
        txtCodigo.setEditable(false);
        txtNombreCategoria.requestFocus();

        String[] tituloTabla = {"CÓDIGO", "Nombre Categoria"};
        modeloCategoria.setColumnIdentifiers(tituloTabla);
        
        txtBuscarCategoria.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:10");
        txtBuscarCategoria.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Código o nombre de categoria");
    }

    private void listarCategoria() {
        Object[] datos = new Object[2];
        for (CategoriaDTO categoria : oCategoria.listar()) {
            datos[0] = categoria.getCodCategoria();
            datos[1] = categoria.getNombreCategoria();
            modeloCategoria.addRow(datos);
        }
        tbCategoria.setModel(modeloCategoria);
    }

    private void limpiarTabla() {
        modeloCategoria.setRowCount(0);
        //modeloEmpleados.getDataVector().removeAllElements();
        //tbEmpleados.removeAll();
    }

    private boolean validarFormulario(String nombreCategoria) {
        if (!nombreCategoria.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos", "¡Error!", JOptionPane.ERROR_MESSAGE);
            txtNombreCategoria.requestFocus();
        }
        return false;
    }

    private void cancelar() {
        txtCodigo.setText("");
        txtNombreCategoria.setText("");

        tbCategoria.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCategoria = new javax.swing.JTable();
        txtBuscarCategoria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnGuardarEmpleado1 = new javax.swing.JButton();
        btnEditarrEmpleado1 = new javax.swing.JButton();
        btnEliminarEmpleado1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnRegresarAProductos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionar Categoría");

        tbCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCategoria);

        txtBuscarCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCategoriaKeyTyped(evt);
            }
        });

        jLabel8.setText("Busca por");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 176, 212), 1, true), "DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(30, 64, 175))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Código:");

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Nombre de categoria:");

        txtNombreCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnGuardarEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnGuardar.png"))); // NOI18N
        btnGuardarEmpleado1.setContentAreaFilled(false);
        btnGuardarEmpleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEmpleado1.setName("btnGuardar"); // NOI18N
        btnGuardarEmpleado1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnGuardarHover.png"))); // NOI18N
        btnGuardarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleado1ActionPerformed(evt);
            }
        });

        btnEditarrEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEditar.png"))); // NOI18N
        btnEditarrEmpleado1.setContentAreaFilled(false);
        btnEditarrEmpleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarrEmpleado1.setName("btnActualizar"); // NOI18N
        btnEditarrEmpleado1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEditarHover.png"))); // NOI18N
        btnEditarrEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarrEmpleado1EmpleadoActionPerformed(evt);
            }
        });

        btnEliminarEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEliminar.png"))); // NOI18N
        btnEliminarEmpleado1.setContentAreaFilled(false);
        btnEliminarEmpleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmpleado1.setName("btnEliminar"); // NOI18N
        btnEliminarEmpleado1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEliminarHover.png"))); // NOI18N
        btnEliminarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleado1EmpleadoActionPerformed(evt);
            }
        });

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCancelar.png"))); // NOI18N
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCancelarHover.png"))); // NOI18N
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnGuardarEmpleado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarrEmpleado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEmpleado1))
                    .addComponent(btnCancelar1))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarrEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegresarAProductos.setText("<-- Regresar");
        btnRegresarAProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(btnRegresarAProductos)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarAProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleado1ActionPerformed
        String nombreCategoria = txtNombreCategoria.getText().trim();
        if (tbCategoria.getSelectedRowCount() == 0) {
            if (validarFormulario(nombreCategoria)) {
                String mensajeJOptionPane;
                JLabel labelMensaje = new JLabel();
                if (!oCategoria.isBuscarNombre(nombreCategoria)) {
                    String mensaje = oCategoria.agregar(nombreCategoria);
                    limpiarTabla();
                    JOptionPane.showMessageDialog(null, mensaje, "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                    cancelar();
                    listarCategoria();
                } else {
                    mensajeJOptionPane = "<html>La categoria <b>" + nombreCategoria + "</b> ya está registrado</html>";
                    labelMensaje.setText(mensajeJOptionPane);
                    JOptionPane.showMessageDialog(null, labelMensaje, "¡Error! Categoria Existe", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Estas En Modo Edición \nHay una categoria seleccionada. \nPresione Cancelar", "¡Error! Acción Inválida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarEmpleado1ActionPerformed

    private void btnEditarrEmpleado1EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarrEmpleado1EmpleadoActionPerformed
        String codCategoria = txtCodigo.getText().trim();
        String nombreCategoria = txtNombreCategoria.getText().trim();
        if (tbCategoria.getSelectedRowCount() > 0) {
            if (validarFormulario(nombreCategoria)) {
                String mensajeJOptionPane;
                JLabel labelMensaje = new JLabel();
                CategoriaDTO dtoCategoria = oCategoria.buscar(codCategoria);
                
                if (dtoCategoria.getNombreCategoria().equals(nombreCategoria)) {
                    String mensaje = oCategoria.actualizar(codCategoria, nombreCategoria);
                    limpiarTabla();
                    JOptionPane.showMessageDialog(null, mensaje, "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                    cancelar();
                    listarCategoria();
                } else {
                    if (!oCategoria.isBuscarNombre(nombreCategoria)) {
                        String mensaje = oCategoria.actualizar(codCategoria, nombreCategoria);
                        limpiarTabla();
                        JOptionPane.showMessageDialog(null, mensaje, "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                        cancelar();
                        listarCategoria();
                    } else {
                        mensajeJOptionPane = "<html>La categoria <b>" + nombreCategoria + "</b> ya está registrado</html>";
                        labelMensaje.setText(mensajeJOptionPane);
                        JOptionPane.showMessageDialog(null, labelMensaje, "¡Error! Categoria Existe", JOptionPane.ERROR_MESSAGE);
                    }
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoria de la tabla.", "¡Error! Acción Inválida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarrEmpleado1EmpleadoActionPerformed

    private void btnEliminarEmpleado1EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleado1EmpleadoActionPerformed
        String codCategoria = txtCodigo.getText().trim();
        if (tbCategoria.getSelectedRowCount() > 0) {
            CategoriaDTO dtoCategoria = new CategoriaDTO();
            dtoCategoria = oCategoria.buscar(codCategoria);
            JLabel labelMensaje = new JLabel();
            String mensajeJOptionPane = "<html>Estas seguro de Eliminar a: <b>" + dtoCategoria.getNombreCategoria() + "</b> </html>";
            labelMensaje.setText(mensajeJOptionPane);
            int opcion = JOptionPane.showConfirmDialog(null, mensajeJOptionPane, "Confirmación de Eliminación", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Toolkit.getDefaultToolkit().beep();
                String mensaje = oCategoria.eliminar(codCategoria);
                limpiarTabla();
                JOptionPane.showMessageDialog(null, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                cancelar();
                listarCategoria();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una categoria de la tabla.", "¡Error! Acción Inválida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarEmpleado1EmpleadoActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        Toolkit.getDefaultToolkit().beep();
        cancelar();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void tbCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCategoriaMouseClicked
        txtCodigo.setText(tbCategoria.getValueAt(tbCategoria.getSelectedRow(), 0).toString());
        txtNombreCategoria.setText(tbCategoria.getValueAt(tbCategoria.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tbCategoriaMouseClicked

    private void btnRegresarAProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAProductosActionPerformed

        if (jFrameAdmin.isVisible()) {
            plProductos panelProductos = new plProductos(jFrameAdmin);
            panelProductos.setSize(1024, 700);
            panelProductos.setLocation(0, 0);
            jFrameAdmin.jpContenedor.removeAll();
            jFrameAdmin.jpContenedor.add(panelProductos, BorderLayout.CENTER);
            jFrameAdmin.jpContenedor.revalidate();
            jFrameAdmin.jpContenedor.repaint();
        } else {
            plProductos panelProductos = new plProductos(jFrameVededor);
            panelProductos.setSize(1024, 700);
            panelProductos.setLocation(0, 0);
            jFrameVededor.contenidoJPanel.removeAll();
            jFrameVededor.contenidoJPanel.add(panelProductos, BorderLayout.CENTER);
            jFrameVededor.contenidoJPanel.revalidate();
            jFrameVededor.contenidoJPanel.repaint();
        }

    }//GEN-LAST:event_btnRegresarAProductosActionPerformed

    private void txtBuscarCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCategoriaKeyTyped
        txtBuscarCategoria.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscarCategoria.getText(), 0));
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscarCategoria.getText(), 1));
            }
        });
        
        trs = new TableRowSorter(modeloCategoria);
        tbCategoria.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarCategoriaKeyTyped

    private void txtNombreCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCategoriaActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnEditarrEmpleado1;
    private javax.swing.JButton btnEliminarEmpleado1;
    private javax.swing.JButton btnGuardarEmpleado1;
    private javax.swing.JButton btnRegresarAProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCategoria;
    private javax.swing.JTextField txtBuscarCategoria;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
