/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BusinessObject.Empleado;
import BusinessObject.Usuario;
import TransferObject.EmpleadoDTO;
import TransferObject.RolUsuarioDTO;
import TransferObject.UsuarioDTO;
import Utilities.Controles;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author KEVIN EP
 */
public class plPerfil extends javax.swing.JPanel {

    private EmpleadoDTO dtoEmpleado;
    private UsuarioDTO dtoUsuario;
    private RolUsuarioDTO dtoRolUsuario;

    private Empleado oEmpleado;
    private Usuario oUsuario;

    private JFrame jFrame;

    /**
     * Creates new form plPerfil
     *
     * @param dtoEmpleado
     * @param dtoUsuario
     * @param dtoRolUsuario
     * @param jFrame
     */
    public plPerfil(EmpleadoDTO dtoEmpleado, UsuarioDTO dtoUsuario, RolUsuarioDTO dtoRolUsuario, JFrame jFrame) {
        initComponents();
        cargarFlatLaft();
        this.dtoEmpleado = dtoEmpleado;
        this.dtoUsuario = dtoUsuario;
        this.dtoRolUsuario = dtoRolUsuario;
        
        this.jFrame = jFrame;

        oEmpleado = new Empleado();
        oUsuario = new Usuario();
        iniciarPanelPerfil();
    }

    private void iniciarPanelPerfil() {
        labelNombresApellidos.setText(dtoEmpleado.getNombres() + " " + dtoEmpleado.getApellidoPaterno() + " " + dtoEmpleado.getApellidoMaterno());
        labelDNI.setText(dtoEmpleado.getDNIEmpleado());
        labelUserName.setText(dtoUsuario.getUserName());
        labelRolusuario.setText(dtoRolUsuario.getNombreRol());
        txtCelular.setText(dtoEmpleado.getCelular());

        btnGuardarCelular.setVisible(false);
        txtCelular.setEditable(false);
    }

    private void cargarFlatLaft() {
        txtCelular.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:10");
        txtUserName.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:12");
        txtPasswordNew.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true;"
                + "showCapsLock:true;"
                + "capsLockIconColor:#333333;"
                + "arc:12;"
        );
        txtPasswordRepeat.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true;"
                + "showCapsLock:true;"
                + "capsLockIconColor:#333333;"
                + "arc:12;"
        );
        txtUserName.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tu nuevo usuario");
        txtPasswordNew.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Contraseña");
        txtPasswordRepeat.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Repite contraseña");
        txtCelular.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tu Nro. Celular");
    }

    public void actualizarUsername(String userName, String codEmpleado) {
        Toolkit.getDefaultToolkit().beep();
        // Actualizamos al usuario 
        String mensaje = oUsuario.actualizarUserName(userName, codEmpleado);
        JOptionPane.showMessageDialog(null, mensaje, "ÉXITO", JOptionPane.INFORMATION_MESSAGE);

        // Preguntar para si desea cerrar sesión para ingresar con su nuevo Nombre de Usuario
        String mensajeCerrarSesion = "<html>¿<b>Deseas cerrar sesión </b> para que ingreses con tu nuevo Nombre de Usuario?</html>";
        JLabel labelMensaje = new JLabel();
        labelMensaje.setText(mensajeCerrarSesion);
        int opcionCrearUsuario = JOptionPane.showConfirmDialog(null, labelMensaje, "Confirmación", JOptionPane.YES_NO_OPTION);
        if (opcionCrearUsuario == JOptionPane.YES_OPTION) {
            frameLogin jpLogin = new frameLogin();
            jFrame.setVisible(false);
            jpLogin.setVisible(true);

        } else {
            txtUserName.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nombresApellidos1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        btnEditarCelular = new javax.swing.JButton();
        btnGuardarCelular = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nombresApellidos2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPasswordNew = new javax.swing.JPasswordField();
        txtPasswordRepeat = new javax.swing.JPasswordField();
        btnActualizarPassword = new javax.swing.JButton();
        nombresApellidos3 = new javax.swing.JLabel();
        btnActualizarUserName = new javax.swing.JButton();
        labelIconoUser = new javax.swing.JLabel();
        labelIconoUser1 = new javax.swing.JLabel();
        labelIconoUser2 = new javax.swing.JLabel();
        labelNombresApellidos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelShadow1 = new Swing.Containers.PanelShadow();
        jLabel2 = new javax.swing.JLabel();
        labelDNI = new javax.swing.JLabel();
        panelShadow2 = new Swing.Containers.PanelShadow();
        jLabel1 = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        panelShadow3 = new Swing.Containers.PanelShadow();
        jLabel6 = new javax.swing.JLabel();
        labelRolusuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nombresApellidos1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nombresApellidos1.setText("Información Personal");

        jLabel3.setText("Revisa y agrega tus datos personales para seguir en contacto.");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Celular:");

        txtCelular.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        btnEditarCelular.setText("Editar");
        btnEditarCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCelularActionPerformed(evt);
            }
        });

        btnGuardarCelular.setText("Guardar");
        btnGuardarCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCelularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(nombresApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nombresApellidos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCelular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Revisa y actualiza tus datos de inicio de sesión.");

        nombresApellidos2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombresApellidos2.setText("Actualiza tu contraseña");

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Nuevo Nombre de Usuario:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Nueva Contraseña:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Repite tu contraseña:");

        txtPasswordNew.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPasswordRepeat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnActualizarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/btnActualizarPassword.png"))); // NOI18N
        btnActualizarPassword.setContentAreaFilled(false);
        btnActualizarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarPassword.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/btnActualizarPasswordHover.png"))); // NOI18N
        btnActualizarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPasswordActionPerformed(evt);
            }
        });

        nombresApellidos3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nombresApellidos3.setText("Información de Acceso al Sistema");

        btnActualizarUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/btnActualizar.png"))); // NOI18N
        btnActualizarUserName.setContentAreaFilled(false);
        btnActualizarUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarUserName.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/btnActualizarHover.png"))); // NOI18N
        btnActualizarUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUserNameActionPerformed(evt);
            }
        });

        labelIconoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/iconUser.png"))); // NOI18N

        labelIconoUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/iconKey.png"))); // NOI18N

        labelIconoUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botones/iconKey.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombresApellidos3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombresApellidos2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelIconoUser))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIconoUser1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelIconoUser2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(txtPasswordNew, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnActualizarPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPasswordRepeat, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnActualizarUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nombresApellidos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIconoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnActualizarUserName))
                .addGap(25, 25, 25)
                .addComponent(nombresApellidos2)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPasswordNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIconoUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPasswordRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIconoUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarPassword)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        labelNombresApellidos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelNombresApellidos.setForeground(new java.awt.Color(0, 0, 0));
        labelNombresApellidos.setText("Nombres y Apellidos");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoPerfilUser.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("DNI");

        labelDNI.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(0, 0, 0));
        labelDNI.setText("72698545");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDNI)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDNI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nombre de Usuario");

        labelUserName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(0, 0, 0));
        labelUserName.setText("Nameuser");

        javax.swing.GroupLayout panelShadow2Layout = new javax.swing.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUserName)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Rol");

        labelRolusuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelRolusuario.setForeground(new java.awt.Color(0, 0, 0));
        labelRolusuario.setText("Nombre Rol");

        javax.swing.GroupLayout panelShadow3Layout = new javax.swing.GroupLayout(panelShadow3);
        panelShadow3.setLayout(panelShadow3Layout);
        panelShadow3Layout.setHorizontalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRolusuario)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panelShadow3Layout.setVerticalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRolusuario)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelNombresApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombresApellidos)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCelularActionPerformed
        btnEditarCelular.setEnabled(false);
        btnGuardarCelular.setVisible(true);
        txtCelular.setEditable(true);
        txtCelular.requestFocusInWindow();
        txtCelular.selectAll();
    }//GEN-LAST:event_btnEditarCelularActionPerformed

    private void btnGuardarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCelularActionPerformed
        String celular = txtCelular.getText();
        if (!celular.isEmpty()) {
            if (celular.startsWith("9") && celular.length() == 9) {
                String mensaje = oEmpleado.actualizarCelular(dtoEmpleado.getCodEmpleado(), celular);
                JOptionPane.showMessageDialog(null, mensaje, "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                btnEditarCelular.setEnabled(true);
                btnGuardarCelular.setVisible(false);
                txtCelular.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Debe tener 9 dígitos y \ncomenzar con el N° 9", "¡Error! N° de Celular no válido", JOptionPane.ERROR_MESSAGE);
                txtCelular.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "El campo celular no debe estar vacío", "¡Error! Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            txtCelular.requestFocus();
        }
    }//GEN-LAST:event_btnGuardarCelularActionPerformed

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        Controles.solonumeros(evt);
        Controles.longitudTexto(evt, txtCelular, 9);
    }//GEN-LAST:event_txtCelularKeyTyped

    private void btnActualizarUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUserNameActionPerformed
        String userName = txtUserName.getText();
        String codEmpleado = dtoUsuario.getCodEmpleado();
        if (!userName.isEmpty()) {

            String dtoUserName = dtoUsuario.getUserName();

            System.out.println(dtoUserName);
            System.out.println(userName);
            System.out.println(dtoUserName.equals(userName));

            if (dtoUserName.equals(userName)) {

                actualizarUsername(userName, codEmpleado);
            } else {
                if (!oUsuario.isBuscarUsuario(userName)) {

                    actualizarUsername(userName, codEmpleado);
                } else {
                    JOptionPane.showMessageDialog(null, "El Nombre de Usuario ya existe", "¡Error!", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "El Nombre de Usuario no debe estar vacío", "¡Error! Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            txtUserName.requestFocus();
        }
    }//GEN-LAST:event_btnActualizarUserNameActionPerformed

    private void btnActualizarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPasswordActionPerformed
        String newPassword = new String(txtPasswordNew.getPassword());
        String repeatPassword = new String(txtPasswordRepeat.getPassword());
        String codEmpleado = dtoUsuario.getCodEmpleado();
        if (!newPassword.isEmpty() && !repeatPassword.isEmpty()) {
            if (newPassword.equals(repeatPassword)) {
                String mensaje = oUsuario.actualizarPassword(newPassword, codEmpleado);
                JOptionPane.showMessageDialog(null, mensaje, "ÉXITO", JOptionPane.INFORMATION_MESSAGE);

                // Preguntar para si desea cerrar sesión para ingresar con su nueva contraseña
                String mensajeCerrarSesion = "<html>¿<b>Deseas cerrar sesión </b> para ingresar con tu nueva contraseña?</html>";
                JLabel labelMensaje = new JLabel();
                labelMensaje.setText(mensajeCerrarSesion);
                int opcionCrearUsuario = JOptionPane.showConfirmDialog(null, labelMensaje, "Confirmación", JOptionPane.YES_NO_OPTION);
                if (opcionCrearUsuario == JOptionPane.YES_OPTION) {
                    frameLogin jpLogin = new frameLogin();
                    jFrame.setVisible(false);
                    jpLogin.setVisible(true);

                } else {
                    txtPasswordNew.setText("");
                    txtPasswordRepeat.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "¡Error! ", JOptionPane.ERROR_MESSAGE);
                txtPasswordRepeat.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Las contraseñas no debe estar vacias", "¡Error! Datos Incompletos", JOptionPane.ERROR_MESSAGE);
            txtPasswordNew.requestFocus();
        }
    }//GEN-LAST:event_btnActualizarPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPassword;
    private javax.swing.JButton btnActualizarUserName;
    private javax.swing.JButton btnEditarCelular;
    private javax.swing.JButton btnGuardarCelular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelIconoUser;
    private javax.swing.JLabel labelIconoUser1;
    private javax.swing.JLabel labelIconoUser2;
    public javax.swing.JLabel labelNombresApellidos;
    public javax.swing.JLabel labelRolusuario;
    public javax.swing.JLabel labelUserName;
    private javax.swing.JLabel nombresApellidos1;
    private javax.swing.JLabel nombresApellidos2;
    private javax.swing.JLabel nombresApellidos3;
    private Swing.Containers.PanelShadow panelShadow1;
    private Swing.Containers.PanelShadow panelShadow2;
    private Swing.Containers.PanelShadow panelShadow3;
    public javax.swing.JTextField txtCelular;
    private javax.swing.JPasswordField txtPasswordNew;
    private javax.swing.JPasswordField txtPasswordRepeat;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
