/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import java.awt.BorderLayout;

/**
 *
 * @author Bryam
 */
public class plReportes extends javax.swing.JPanel {

    /**
     * Creates new form plReportes
     */
    public plReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReportesClientes = new javax.swing.JButton();
        btnReportesProductos = new javax.swing.JButton();
        btnReportesVisitas = new javax.swing.JButton();
        btnReportesVentas1 = new javax.swing.JButton();
        plContenedorReportes = new javax.swing.JPanel();

        btnReportesClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportesClientes.setText("CLIENTES");
        btnReportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesClientesActionPerformed(evt);
            }
        });

        btnReportesProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportesProductos.setText("PRODUCTOS");

        btnReportesVisitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportesVisitas.setText("VISITAS");
        btnReportesVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesVisitasActionPerformed(evt);
            }
        });

        btnReportesVentas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportesVentas1.setText("VENTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnReportesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportesProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportesVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportesVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 494, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnReportesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnReportesProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnReportesVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnReportesVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout plContenedorReportesLayout = new javax.swing.GroupLayout(plContenedorReportes);
        plContenedorReportes.setLayout(plContenedorReportesLayout);
        plContenedorReportesLayout.setHorizontalGroup(
            plContenedorReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        plContenedorReportesLayout.setVerticalGroup(
            plContenedorReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(plContenedorReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plContenedorReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesClientesActionPerformed
        // TODO add your handling code here:
        plReporteClientes pReporteCliente = new plReporteClientes();
        pReporteCliente.setSize(1024, 549);
        pReporteCliente.setLocation(0,0);
        plContenedorReportes.removeAll();
        plContenedorReportes.add(pReporteCliente, BorderLayout.CENTER);
        plContenedorReportes.revalidate();
        plContenedorReportes.repaint();
    }//GEN-LAST:event_btnReportesClientesActionPerformed

    private void btnReportesVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesVisitasActionPerformed
        // TODO add your handling code here:
        plReporteVisitas pReporteVisita = new plReporteVisitas();
        pReporteVisita.setSize(1024, 549);
        pReporteVisita.setLocation(0,0);
        plContenedorReportes.removeAll();
        plContenedorReportes.add(pReporteVisita, BorderLayout.CENTER);
        plContenedorReportes.revalidate();
        plContenedorReportes.repaint();
    }//GEN-LAST:event_btnReportesVisitasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportesClientes;
    private javax.swing.JButton btnReportesProductos;
    private javax.swing.JButton btnReportesVentas1;
    private javax.swing.JButton btnReportesVisitas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel plContenedorReportes;
    // End of variables declaration//GEN-END:variables
}
