/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BusinessObject.Cliente;
import BusinessObject.Visita;
import TransferObject.ClienteDTO;
import TransferObject.VisitaDTO;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import BusinessObject.Cliente;
import BusinessObject.Visita;
import static Presentacion.plReporteTablaVisita.tbReporteVisitas;
import TransferObject.ClienteDTO;
import TransferObject.VisitaDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Bryam
 */
public class plReporteTablaVisita extends javax.swing.JPanel {

    DefaultTableModel modelo;
    VisitaDTO visitaDTO;
    String personajuridica;
    Visita visita;

    /**
     * Creates new form plReporteTipoEmpleado
     */
    public plReporteTablaVisita() {
        initComponents();
        modelo = new DefaultTableModel();
        visitaDTO = new VisitaDTO();
        visita = new Visita();
        //cargaDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReporteVisitas = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 176, 212), 2, true)));

        tbReporteVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO VISITA", "CODIGO EMPLEADO", "CODIGO CLIENTE", "FECHA", "VENTA", "VER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbReporteVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReporteVisitasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbReporteVisitasMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbReporteVisitasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbReporteVisitasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbReporteVisitas);
        if (tbReporteVisitas.getColumnModel().getColumnCount() > 0) {
            tbReporteVisitas.getColumnModel().getColumn(1).setResizable(false);
            tbReporteVisitas.getColumnModel().getColumn(3).setResizable(false);
            tbReporteVisitas.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbReporteVisitasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReporteVisitasMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbReporteVisitasMousePressed

    private void tbReporteVisitasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReporteVisitasMouseReleased
        // TODO add your handling code here:
        //tbReporteVisitas.setColumnSelectionInterval(0, 4);

    }//GEN-LAST:event_tbReporteVisitasMouseReleased

    private void tbReporteVisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReporteVisitasMouseClicked
        // TODO add your handling code here:
        //if (evt.getButton() == MouseEvent.BUTTON1) {
        // Obtener la fila en la que se hizo clic
        int columna = plReporteTablaVisita.tbReporteVisitas.getColumnModel().getColumnIndexAtX(evt.getX());
        int fila = evt.getY() / plReporteTablaVisita.tbReporteVisitas.getRowHeight();
        
        if (fila < plReporteTablaVisita.tbReporteVisitas.getRowCount() && fila >= 0 && columna < plReporteTablaVisita.tbReporteVisitas.getColumnCount() && columna >= 0) {
                Object value = plReporteTablaVisita.tbReporteVisitas.getValueAt(fila, columna);
                if (value instanceof JButton) {
                    ((JButton) value).doClick();
                    JButton boton = (JButton) value;

                    if (boton.getName().equals("Ver")) {
                        JOptionPane.showMessageDialog(null, "Probando");

                        
                    }
                }
            }
        
    //}
    }//GEN-LAST:event_tbReporteVisitasMouseClicked

    private void tbReporteVisitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReporteVisitasMouseEntered
        // TODO add your handling code here:
        int fila = plReporteTablaVisita.tbReporteVisitas.rowAtPoint(evt.getPoint());
        
        int columna = plReporteTablaVisita.tbReporteVisitas.columnAtPoint(evt.getPoint());

        // Verificar si el evento ocurrió en la columna de botones
        if (columna == 5) {
            JButton boton = (JButton) plReporteTablaVisita.tbReporteVisitas.getValueAt(fila, columna);
            boton.setBackground(Color.RED); // Cambiar el color del botón al entrar
        }
    }//GEN-LAST:event_tbReporteVisitasMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbReporteVisitas;
    // End of variables declaration//GEN-END:variables
}
