/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BusinessObject.Cliente;
import TransferObject.ClienteDTO;
import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryam
 */
public class plReporteClientes extends javax.swing.JPanel {
    DefaultTableModel modelo;
    ClienteDTO clienteDTO;
    String personajuridica;
    Cliente cliente;
    /**
     * Creates new form plReporteClientes
     */
    public plReporteClientes() {
        initComponents();
        modelo = new DefaultTableModel();
        clienteDTO = new ClienteDTO();
        cliente = new Cliente();
        
    }
    
    public void cargarPersonaNatural() {
        
        try {
            modelo = (DefaultTableModel) plReporteTablaCliente.tbReporteClientes.getModel();
            Object[] ob = new Object[8];
            for (ClienteDTO p : cliente.listarPersonaNatural()) {
                ob[0] = p.getCodCliente();
                ob[1] = p.getRuc();
                ob[2] = p.getRazonsocial();
                ob[3] = p.getNombrecomercial();
                ob[4] = p.getDireccionfiscal();
                ob[5] = p.getCelular();
                ob[6] = p.getDistrito();
                ob[7] = p.getProvincia();
                modelo.addRow(ob);
            }
            plReporteTablaCliente.tbReporteClientes.setModel(modelo);
        } catch (Exception ex) {

        }
        
    }
    
    public void cargarPersonaJuridica() {
        
        try {
            modelo = (DefaultTableModel) plReporteTablaCliente.tbReporteClientes.getModel();
            Object[] ob = new Object[8];
            for (ClienteDTO p : cliente.listarPersonaJuridica()) {
                ob[0] = p.getCodCliente();
                ob[1] = p.getRuc();
                ob[2] = p.getRazonsocial();
                ob[3] = p.getNombrecomercial();
                ob[4] = p.getDireccionfiscal();
                ob[5] = p.getCelular();
                ob[6] = p.getDistrito();
                ob[7] = p.getProvincia();
                modelo.addRow(ob);
            }
            plReporteTablaCliente.tbReporteClientes.setModel(modelo);
        } catch (Exception ex) {

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoCliente = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbtnJuridica = new javax.swing.JRadioButton();
        rbtnNatural = new javax.swing.JRadioButton();
        btnMostrar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        plContenedorReporteCliente = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 176, 212), 2, true)));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 176, 212), 2, true), "TIPO DE CLIENTE"));

        btngTipoCliente.add(rbtnJuridica);
        rbtnJuridica.setText("Jurídica");

        btngTipoCliente.add(rbtnNatural);
        rbtnNatural.setText("Natural");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnJuridica)
                    .addComponent(rbtnNatural))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnJuridica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnNatural)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnImprimir.setText("IMPRIMIR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir)
                .addContainerGap(636, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        plContenedorReporteCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 176, 212), 2, true)));

        javax.swing.GroupLayout plContenedorReporteClienteLayout = new javax.swing.GroupLayout(plContenedorReporteCliente);
        plContenedorReporteCliente.setLayout(plContenedorReporteClienteLayout);
        plContenedorReporteClienteLayout.setHorizontalGroup(
            plContenedorReporteClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        plContenedorReporteClienteLayout.setVerticalGroup(
            plContenedorReporteClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(plContenedorReporteCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plContenedorReporteCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        plReporteTablaCliente pReporteCliente = new plReporteTablaCliente();
        pReporteCliente.setSize(1020, 549);
        pReporteCliente.setLocation(0,0);
        plContenedorReporteCliente.removeAll();
        plContenedorReporteCliente.add(pReporteCliente, BorderLayout.CENTER);
        plContenedorReporteCliente.revalidate();
        plContenedorReporteCliente.repaint();
        
        if (plReporteClientes.rbtnNatural.isSelected()){
            cargarPersonaNatural();
        }
        
        if (plReporteClientes.rbtnJuridica.isSelected()){
            cargarPersonaJuridica();
        }
        
        
        
        
    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMostrar;
    private javax.swing.ButtonGroup btngTipoCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel plContenedorReporteCliente;
    public static javax.swing.JRadioButton rbtnJuridica;
    public static javax.swing.JRadioButton rbtnNatural;
    // End of variables declaration//GEN-END:variables
}
